@startuml component-diagram
title Diagrama de Componentes

package "Frontend" {
    package "domains"{
        package "auth"{
            package "application" {
                [AuthService]
            }
            package "components" {
                [ForgotPasswordForm]
                [LoginForm]
                [ResetPasswordForm]
                [SignUpForm]
                [VerificationCodeForm]
            }
            package "pages" {
                [ForgotPasswordPage]
                [LoginPage]
                [ResetPasswordPage]
                [SignUpPage]
                [VerificationCodePage]
            }
            package "schemas" {
                [emailverification]
                [forgotpassword]
                [login]
                [resetpassword]
                [signup]
            }
        }
        
    }
    package "shared"{
        package "components-shared" {
            [Button]
            [Card]
            [Input-otp]
            [Input]
            [Label]
            [Separator]
            [Toaster]
        }
        package "layouts" {
            [AuthLayout]
        }
    }
}

package "Backend"{
    package "User" {
        package "User :: controller" {
            [UserController]
        }
        package "User :: service" {
            [UserService]
        }
        package "User :: repository" {
            [UserRepository]
        }
        package "User :: entity" {
            [UserEntity]
        }
        package "User :: dto"{
            [SignUpRequest]
            [LoginRequest]
            [AuthUserRequest]
            [ForgotPasswordRequest]
            [ResetPasswordRequest]
            [UserResponse]
        }
    }
    package "infraestructure" {
        package "config" {
            [OTPCleanupService]
            [SecurityConfig]
        }
        package "email" {
            [EmailService]
        }
        package "one_time_password" {
            package "one_time_password :: entity" {
                [One_Time_Password]
            }
            package "one_time_password :: service" {
                [One_Time_PasswordService]
            }
            package "one_time_password :: repository" {
                [One_Time_PasswordRepository]
            }
        }
        package "purpose_otp"{
            package "purpose_otp :: entity" {
                [Purpose_OTP]
            }
            package "purpose_otp :: service" {
                [Purpose_OTPService]
            }
            package "purpose_otp :: repository" {
                [Purpose_OTPRepository]
            }
        }
    }
    package "Test" {
        package "unit-tests" {
            package "User-Tests" {
                [UserTest]
            }
        }
        
    }
}

database "PostgreSQL"

' ===========================
'       Relationships: Frontend
' ===========================
[pages] -> [components]
[pages] -> [layouts]
[components] --> [schemas]
[components] -> [components-shared]
[application] -> [components]

' ===========================
'       Relationships: Frontend -> Backend
' ===========================
[AuthService] --> [UserController]

' ===========================
'       Relationships: Controller -> Service
' ===========================
[UserController] --> [UserService]

' ===========================
'       Relationships: Service -> Service
' ===========================
[UserService] --> [One_Time_PasswordService]
[UserService] --> [EmailService]

' ===========================
'       Relationships: Service -> Repository
' ===========================
[UserService] --> [UserRepository]
[One_Time_PasswordService] --> [One_Time_PasswordRepository]
[Purpose_OTPService] --> [Purpose_OTPRepository]

' ===========================
'       Relationships: Service -> DTO
' ===========================
[UserService] --> [dto]
' ===========================
'       Relationships: Repository -> Entity
' ===========================
[UserRepository] --> [UserEntity]
[One_Time_PasswordRepository] --> [One_Time_Password]
[Purpose_OTPRepository] --> [Purpose_OTP]

' ===========================
'       Relationships: Repository -> BD
' ===========================
[UserRepository] --> PostgreSQL

@enduml
