@startuml component-diagram
title Diagrama de Componentes
package "Frontend"{
    [index.html]
    package "src" as src_frontend{
        [main.tsx]
        package "app"{
            package "contexts"{
                [PrivateRoute.tsx]
                [UserContext.tsx]
            }
            package "domains"{
                package "shared"{
                    package "components-shared"{
                        [set<ComponentsShared.tsx>]
                    }
                    package "layouts"{
                        [set<Layouts.tsx>]
                    }
                    package "lib"{
                        [utils.ts]
                    }
                    package "pages" as shared_pages{
                        [set<SharedPages.tsx>]
                    }
                }
                package "domain"{
                    package "application" {
                        [set<DomainService.ts>]
                    }
                    package "components" {
                        [set<DomainComponents.tsx>]
                    }
                    package "pages" as domain_pages{
                        [set<DomainPages.tsx>]
                    }
                    package "schemas" {
                        [set<Schemas.ts>]
                    }
                }
            }
        }
        package "i18n"{
            package "locales"{
                [set<locales.json>]
            }
        }
    }
}

package "Backend"{
    package "src" as src_backend{
        package "main"{
            package "java/com/TFG/app/backend" as backend{
                package "name-entity"{
                    package "entity"  as entity{
                        [Entity.java]
                    }
                    package "service" {
                        [EntityService.java]
                    }
                    package "controller" {
                        [EntityController.java]
                    }
                    package "repository" {
                        [EntityRepository.java]
                    }
                    package "dto" {
                        [set<Dtos.java>]
                    }
                }
                package "resources"{
                    package "messages"{
                        [set<messages.properties>]
                    }
                }
                [BackendApplication.java]
            }
        }
        package "test"{
            package "java/com/TFG/app/backend" as backend_test{
                [BackendApplicationTests.java]
                package "name-entity" as entity_test{
                    [EntityUnitTest.java]
                    [EntityIntegrationTest.java]
                }
            }
        }
        
    }
}
database "PostgreSQL"

'------
' Relationships - Frontend
'------

[index.html] --> [main.tsx]
[PrivateRoute.tsx] --> [UserContext.tsx]
[main.tsx] --> [PrivateRoute.tsx]
[main.tsx] --> [set<SharedPages.tsx>]
[main.tsx] --> [set<DomainPages.tsx>]
[set<DomainPages.tsx>] --> [set<DomainComponents.tsx>]
[set<DomainPages.tsx>] --> [set<DomainService.ts>]
[set<DomainPages.tsx>] --> [set<ComponentsShared.tsx>]
[set<DomainComponents.tsx>] --> [set<ComponentsShared.tsx>]
[set<DomainPages.tsx>] --> [set<Layouts.tsx>]
[set<ComponentsShared.tsx>] --> [utils.ts]
[set<DomainComponents.tsx>] --> [set<Schemas.ts>]
[set<DomainComponents.tsx>] --> [set<locales.json>]
[set<Layouts.tsx>] --> [set<locales.json>]
'------
' Relationships - Backend
'------

[EntityController.java] --> [EntityService.java]
[EntityService.java] --> [EntityRepository.java]
[EntityController.java] --> [set<Dtos.java>]
[EntityService.java] --> [Entity.java]
[EntityService.java] --> [set<messages.properties>]
[EntityRepository.java] --> [Entity.java]
[EntityRepository.java] --> [PostgreSQL]
[BackendApplicationTests.java] --> [EntityUnitTest.java]
[BackendApplicationTests.java] --> [EntityIntegrationTest.java]
'------
' Relationships - Backend - Frontend
'------
[EntityController.java] --> [set<DomainService.ts>]
[set<DomainService.ts>] --> [EntityController.java]
@enduml