spring.application.name=backend
server.port=8081
spring.security.user.name=admin
spring.security.user.password={noop}admin
spring.datasource.url=jdbc:postgresql://localhost:5432/tfg
spring.datasource.username=postgres
spring.datasource.password=usuario
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moneysaver.noreply@gmail.com
spring.mail.password=xctz swks gjyw yhuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.scheduler-name=CategoryMonthlyResetScheduler
spring.quartz.overwrite-existing-jobs=true
